### ISSUE TITLE
Incorrect joining instructions in public email

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#101]
Public notifications for events contains the link to *edit the event" and not the one to simply see the joining instructions:
```
 Instructions are restricted to meeting participants. You need to [ log in](https://auth.w3.org/?url=https%3A%2F%2Fwww.w3.org%2Fevents%2Fmeetings%2F59430e2c-7ebc-4cc1-9389-b3942d721faa%2F20230510T120000%2Fedit) to see them.
```
https://lists.w3.org/Archives/Public/public-json-ld-wg/2023Apr/0008.html

Since most participant cannot edit the event, they won't be able to see the instructions.

It should read instead:
```
 Instructions are restricted to meeting participants. You need to [ log in](https://auth.w3.org/?url=https%3A%2F%2Fwww.w3.org%2Fevents%2Fmeetings%2F59430e2c-7ebc-4cc1-9389-b3942d721faa%2F20230510T120000) to see them.
```

**Comment by jean-gui** [comment]
This should be fixed now
