### ISSUE TITLE
Many groups have not posted enough details in the calendar

### ISSUE THREAD

**Issue by mitchellevan** [w3c/calendar#108]
This is probably more of an organizational problem than a technical one.

As a first-time TPAC member, I started by assuming any information I would need as an observer would be found in the calendar and its website. I spoke with @daniel-montalvo who confirmed this was a reasonable assumption.

However, a number of groups did not list agendas or background reading on the calendar even by the start time of the sessions. Worse than not having the preparatory information, as a participant I did not even know that there was preparatory information.

**Comment by vivienlacourba** [comment]
Hi @mitchellevan, I agree that detailed agendas with backgroun dreading is very useful and that it seems more like a organizational issue for our Projects and Events teams (cc: @plehegar and @alexandralacourba).

May I know which TPAC events you looked at? If you have link to specific events that were lacking proper agenda that would be useful.

**Comment by mitchellevan** [comment]
Difficulty: This is the first session I attended. Participation depended on locating meeting materials in real-time during the meetings, and there were no external links from the calendar page:
https://www.w3.org/events/meetings/8086a831-b0f8-462e-9d73-ffdbfd1b20a5/

Difficulty: I did not attend this one, but I might have observed if they had provided an agenda:
https://www.w3.org/events/meetings/b2db2f06-ff72-4365-a067-5df39cf2fcd6/

Good: I attended as an observer for a portion that interested me on the agenda, and it had links to 
https://www.w3.org/events/meetings/440affc9-1de1-4036-b97e-66fd97d51bac/

Good: Most of the breakouts I attended had links to the presentation materials.
https://www.w3.org/events/meetings/0b41175f-1b8d-46dd-be64-24335633dc04/
https://www.w3.org/events/meetings/fcde7756-f9a9-4ad5-b67a-0d7049e5b10b/
https://www.w3.org/events/meetings/9f1667d4-a23b-4893-80aa-06d5ecca8434/
https://www.w3.org/events/meetings/04553884-088e-41b5-9a16-5e46caca6c55/

Fair: This breakout provided a session description and a link to related materials, but not a link to the presentation itself.
https://www.w3.org/events/meetings/ed5925cb-c1de-43ff-b7d3-7411ce8d0d84/

Even among the "good" ones, there was not always a clear persistent pointer to the IRC channel. If they said it out loud or presented it briefly on a slide, it was easy to miss. I would then miss subsequent links during the session, and (for breakouts) opportunities to join the queue.

**Comment by vivienlacourba** [comment]
Thanks @mitchellevan for your feedback. I have forwarded it to the Project and Events leads hoping they will address it for the next TPAC.

**Comment by alexandralacourba** [comment]
@mitchellevan, groups have been reminded several times to state the meeting details on the calendar such as agenda, IRC channels, etc. We will make sure that next time, all groups do so. We are sorry for the inconvenience caused.
