### ISSUE TITLE
Can't reset recurring meeting if started too late

### ISSUE THREAD

**Issue by wseltzer** [w3c/calendar#11]
Steps to reproduce: 
* Set a PSIG meeting for "every 1 month, second Monday"
* Begin date was set to May (don't know if that was user error)
* Attempt to reschedule to begin in April, calendar doesn't add a May meeting
* Don't see anyplace to update the recurrence setting, whether in "edit this event" or "edit this and future"
Further, when I try to update again, getting various "this value should not be blank" errors even with the fields filled. 

https://www.w3.org/events/meetings/49b2e79d-e9b4-4381-a25c-a19a93a53132/20210510T120000/edit-future

**Comment by jean-gui** [comment]
Should be fixed
