### ISSUE TITLE
Time zone Converter open in new window

### ISSUE THREAD

**Issue by iadawn** [w3c/calendar#111]
Adding a new event under Time zone there is a link to [Time zone Converter](https://www.timeanddate.com/worldclock/converter.html). If this is activated it opens the page in the same tab/window. On returning to the form with the back button, the form is reset to the empty state.

Suggestion: open the link in a new tab (with appropriate marker that this will happen)

**Comment by jean-gui** [comment]
Done. Can you confirm?

**Comment by iadawn** [comment]
Could you change from:

```
Search time zones by GMT offset, major city or time zone name.
<a href="https://www.timeanddate.com/worldclock/converter.html" target="_blank">Time zone
Converter</a> (opens in a new window)
```

to

```
Search time zones by GMT offset, major city or time zone name.
<a href="https://www.timeanddate.com/worldclock/converter.html" target="_blank">Time zone
Converter (opens in a new window)</a>
```

It is fine to include a `<span>` around the '(opens in new window)' to style it differently. But the text really needs to be inside the link.

**Comment by jean-gui** [comment]
Done.
