### ISSUE TITLE
Reactivate cancelled events

### ISSUE THREAD

**Issue by iherman** [w3c/calendar#114]
Once an even has been marked as cancelled, it is not possible to re-activate it. Would it be possible to do that?

Why? We are all humans, meaning it may happen that one cancels the wrong item. But, in this case, there is no way to redeem...

**Comment by svgeesus** [comment]
Related:

 - https://github.com/w3c/calendar/issues/92
 - https://github.com/w3c/calendar/issues/39
 - https://github.com/w3c/calendar/issues/90

**Comment by simoneonofri** [comment]
There was a recent issue on the WebAuthn group as well, actually, it would be a great enhancement

**Comment by jean-gui** [comment]
It should now be possible to uncancel events.
