### ISSUE TITLE
Add a join link in the calendar entry list

### ISSUE THREAD

**Issue by xfq** [w3c/calendar#115]
https://www.w3.org/groups/wg/i18n-core/calendar/

Is it possible to add a join link in the calendar entry list (maybe displaying it 15 minutes or so before the start of the meeting)?

<img width="827" alt="join" src="https://github.com/w3c/calendar/assets/2863444/461b4efa-c8f2-4396-9092-607d7a30364d">

Some attendees of our telecon didn't realise that they needed to click through the calendar entry to see the join link, which caused some confusion, and we thought it would be useful to add a join link in the entry that will start soon on the calendar list page. Thank you!

**Comment by fantasai** [comment]
+1 to this request! I have often wanted exactly this.

**Comment by vivienlacourba** [comment]
I believe this has already been implemented. Asking @jean-gui to confirm.

**Comment by jean-gui** [comment]
Yes, that there is indeed a button to join a meeting if it is in progress or starts soon

**Comment by xfq** [comment]
I don't think this issue is fixed. I was talking about a button in the calendar entry **list**. See the picture and description above.

I have a meeting starting right now, but I don't see this button.

**Comment by jean-gui** [comment]
@xfq can you please send me the url of the event in question?

**Comment by jean-gui** [comment]
FYI, this is how it should look:
![Screenshot_20241120_154226](https://github.com/user-attachments/assets/c324df06-d999-471d-a53c-2296aee946d7)

**Comment by xfq** [comment]
I just added a test event to my group and it seems to work. I may not have logged into calendar yesterday. Sorry for the noise.

Closing this issue. Thank you, @jean-gui!
