### ISSUE TITLE
Change event reminder

### ISSUE THREAD

**Issue by iadawn** [w3c/calendar#119]
If I am subscribed to a calendar, events have an alert/notification set to 15 seconds before the start of the meeting as a default in Mac calendar. There is no alert/notification in my Google calendar.

Any way to change this?

**Comment by jean-gui** [comment]
Hi @iadawn,

In Google Calendar there is an "Event notifications" section in the subscribed calendar settings. Is that what you're looking for?

**Comment by iadawn** [comment]
Ah ha!!!
