### ISSUE TITLE
Is "until" inclusive or exclusive?

### ISSUE THREAD

**Issue by wseltzer** [w3c/calendar#12]
Bug: I expected that if I put "until" 2d Monday of December, a meeting would be scheduled for that day. Instead, recurring meetings were scheduled only through November.  

This could be solved either with a change of behavior or a UI note.

**Comment by jean-gui** [comment]
It is supposed to be inclusive. Do you have a link to that event? Or do you remember how you created it (start, end, timezone, recurrence pattern)?

**Comment by wseltzer** [comment]
https://www.w3.org/events/meetings/65a2f547-260b-4aed-b8f9-4f048b3a7501/edit#general (it happened again, creating a new PSIG invite)

**Comment by jean-gui** [comment]
That seems to be due to the time zone not being applied properly to the "until" date. I'll look into it.

**Comment by jean-gui** [comment]
Should be fixed. Turns out it was indeed related to time zones and daylight saving.
