### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by wseltzer** [w3c/calendar#14]
* Who gets emails when an event is added/updated? As event creator (team contact), I'd like to know whom I'm spamming with email when updating an event. Do all state changes send email, or is "draft" a way to test things before sending notifications?  [[I hear it emails only when important changes are made (dates, invitees,joining instructions, location)]]

* Drafts. Note that "drafts" are linked from https://www.w3.org/users/myprofile/calendar . Can we offer the https://www.w3.org/users/myprofile/calendar/drafts link in more obvious places in the event creation flow? 

* Drafts feature request: Show an icon or "recurring" indicator for meetings that have recurrence set.

**Comment by vivienlacourba** [comment]
Hi Wendy,

> * Who gets emails when an event is added/updated? As event creator (team contact), I'd like to know whom I'm spamming with email when updating an event. Do all state changes send email, or is "draft" a way to test things before sending notifications?  [[I hear it emails only when important changes are made (dates, invitees,joining instructions, location)]]
> 
> * Drafts. Note that "drafts" are linked from https://www.w3.org/users/myprofile/calendar . Can we offer the https://www.w3.org/users/myprofile/calendar/drafts link in more obvious places in the event creation flow?

Having discuss this with @jean-gui here is our thinking:

If current status == DRAFT
=> Add a message on the edit form (which will be removed as soon as the status field value is changed) indicating:
> This event is a Draft only visible by its creator and chairs and team contacts of participating groups.
> While it remains in that state if you update it no notifications will be sent to participants.
> You can find this event from your ["My calendar / Draft"](https://www.w3.org/users/myprofile/calendar/drafts) page.

If status != DRAFT and a significant change was made
=> display this message:
> You have modified a significant information of the event.
> A notification will be sent to the participants to inform them of this change.

Does this looks good to you?

Vivien

**Comment by plehegar** [comment]
(waiting on proposal in #24 to get implemented)

**Comment by vivienlacourba** [comment]
Closing. This was implemented long ago along with #24 and #34.
