### ISSUE TITLE
Canceling a draft event shouldn't notify the Group

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#15]
I deleted a draft event and it generated an email notification to the Group:
  https://lists.w3.org/Archives/Public/public-pointer-events/2021JanMar/0104.html

**Comment by jean-gui** [comment]
When you clicked the delete button, did you also change the status to tentative or confirmed? That would explain why the email was sent and I'll need to fix this.
If you didn't, the problem lies elsewhere.

**Comment by plehegar** [comment]
I did not change the status before deleting the event.

**Comment by jean-gui** [comment]
Fixed.
