### ISSUE TITLE
"Event Changed" when Draft->Confirmed

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#16]
https://lists.w3.org/Archives/Public/public-pointer-events/2021JanMar/0105.html

Title is "Event Changed: March 17 Call"

However, the mailing list was never notified before since it was a draft.

So, technically, the event was changed from Draft -> Confirmed, but for participants, it's the first time they are receiving the notification so it's not a change for them but a new event.

**Comment by jean-gui** [comment]
Fixed. It should now read "Event Invitation"
