### ISSUE TITLE
Notification is missing when a "Draft" event is created

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/calendar#17]
I did a quick test-drive, and created a recurring Web Fonts WG call entry (without adding sensitive password details) to see what members vs. non-members would see. So far, everything seem to work just fine, with the only caveat :
- when I created the meeting entry as a "Draft", I didn't get any notification about it, nada! (I was expecting a notification with the link to modify the event.)
- when I went back and modified the status of the event as "Tentative", I saw two notifications sent - one addressed directly to me with all the "Joining" details included in cleartext, and another one sent to the public WG list with "Joining" details replaced by the login link (good!)

This is my experience so far. Without knowing what to expect it is hard to decide if the lack of notification about creations of the draft event is a bug, or is it by design - a notification would be useful because the "draft" has to be modified at some point to make it an event. I was expecting an email (sent ONLY to the person who created the draft event) with the link to edit it.

**Comment by plehegar** [comment]
Note that 'Draft' doesn't make the event as part of the Group calendar yet, unlike 'Tentative'/'Confirmed'. As long as it remains as 'Draft', you can safely modify the event without sending notifications.

Announcements are only sent out for 'Tentative' and 'Confirmed' events and when important changes are made (dates, status, recurrence rule, invitees, joining instructions, location).

**Comment by plehegar** [comment]
(waiting on proposal in #24  to get implemented)

**Comment by jean-gui** [comment]
@plehegar #24 has been implemented

**Comment by plehegar** [comment]
closing with no action. Re-open this if you truly believe 'Draft" should snd notifications.
