### ISSUE TITLE
Adding an Agenda URL and no agenda text gives an error

### ISSUE THREAD

**Issue by jnurthen** [w3c/calendar#18]
The error cannot be seen on the screen as the screen repaints.

https://user-images.githubusercontent.com/1724479/111389871-f6331700-866e-11eb-8c27-02e5f483e0e5.mov

**Comment by jnurthen** [comment]
Seems like the error is on the first page and is invalid

<img width="1133" alt="Screen shot showing a field with Field cannot be blank but there is text in the field" src="https://user-images.githubusercontent.com/1724479/111390026-45794780-866f-11eb-84dc-30e312a5f1b8.png">

**Comment by jean-gui** [comment]
@jnurthen The issue should be fixed.
I'm keeping it open as the fact you didn't see the error immediately reveals that I need to find a way to improve error reporting.

**Comment by jean-gui** [comment]
@jnurthen I have improved how errors are being reported. There's now a box at the top of the form indicating there are errors, and tabs containing errors are highlighted.

![Screenshot_20210401_185244](https://user-images.githubusercontent.com/1479073/113327909-d3199000-931b-11eb-8e0a-220c43bec797.png)
