### ISSUE TITLE
Getting back to the WG

### ISSUE THREAD

**Issue by iherman** [w3c/calendar#19]
(I put this on the mailing list; sorry, I forgot about this repository)

A minor UI issue.

Let us say I go to a specific event (I get it by email, or it lingers in my browser), say,

https://www.w3.org/events/meetings/ecb4fdfa-359b-4e2e-b8c9-047fb0addc66/20210319T090000

this event is 'owned' by a WG (the EPUB WG in this case). However, there is button on the screen to at least lead me to that WG's admin page, ie:

https://www.w3.org/groups/wg/epub

or, alternatively, to

https://www.w3.org/groups/wg/epub/calendar

If one wants to add new events for the same group, it becomes a bit complicated…

**Comment by vivienlacourba** [comment]
Hi @iherman;

Technically the event is not "owned" by the "EPUB 3 Working Group", the WG is only of its participants (and in that case it is the sole participant, but there could very well be multiple groups participating to this event).

Under **Participants** you will find links to enable you to go back to either the [EPUB3 WG group page](https://www.w3.org/groups/wg/epub) or [its calendar page](https://www.w3.org/groups/wg/epub/calendar):

![image](https://user-images.githubusercontent.com/2012282/111450586-d3f1d580-8710-11eb-8436-f9a0adf979bf.png)

Let me know if that answers your question or if you have suggestion to improve this.

**Comment by iherman** [comment]
You are right, I missed this! My bad.
