### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by iherman** [w3c/calendar#20]
An image is worth a thousand words... I 'just' tried to extend the series until the end of the charter, and I got this:

![Screen Shot 2021-03-17 at 08 59 11](https://user-images.githubusercontent.com/520723/111434598-0515da00-8700-11eb-901c-65a46eadc684.png)

???

**Comment by iherman** [comment]
To be clear, I realize I made a mistake by using the wrong menu item for the end date (I could change the event since), but the error messages are unclear.

**Comment by jean-gui** [comment]
Duplicate of #18

**Comment by espinr** [comment]
I got the same problem. Always when I try to edit an event to change the status.

**Comment by jean-gui** [comment]
The problem should be fixed.
