### ISSUE TITLE
Delay emails when creating an event

### ISSUE THREAD

**Issue by iherman** [w3c/calendar#21]
A disagreeable side effect of the current design is that if the person creating a new event makes a mistake, then the mailing list is flooded by wrong emails. A typical case is (which happened to me): I set up a repeated event, validated it and, a few minutes later I realized I had made a mistake (set every day instead of every week). Result: all WG members get a wrong email, then a proper one. Which is a drag for Working Group members.

Is there a possibility to 'delay' such mails to let the creator of the event check everything?

**Comment by plehegar** [comment]
This got fixed in the latest iteration. You can now select "but don't send notifications"
