### ISSUE TITLE
duration of the calendar event must be shorter than how frequently it occurs?!?

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#25]
Regarding:
  https://www.w3.org/events/meetings/28d91e83-bc19-408e-816b-32ed7e9bd52e/20210324T070000

when trying save the event via the .ics link, one gets "The duration of the calendar event must be shorter than how frequently it occurs."

cc @nigelmegitt

**Comment by jean-gui** [comment]
I suppose the ics link was the "Download all occurrences as ics" one, right?
Which client are you getting this error from?

Lightning happily imported this file, and its content looks good to me. Do you happen to have a more detailed version of the error?

**Comment by nigelmegitt** [comment]
It was Outlook for Mac (O365 version). That was the error message. The recurrence on the event.ics file did appear to be shorter than the meeting duration.

**Comment by jean-gui** [comment]
I've ran some tests on the evaluation version of Outlook for Windows and also had issues importing https://www.w3.org/events/meetings/28d91e83-bc19-408e-816b-32ed7e9bd52e/export, although I didn't get the same error. I got:
`
Task 'Internet Calendars' reported error (0x00070032) : 'The VEVENT, "W3C Process CG Call", defined near line 27, contains a recurrence pattern that Outlook does not support. The appointment has been skipped.'`
`

Apparently Outlook doesn't support recurrences such as "2nd and 4th Tuesdays every month". Google Agenda is a little better as it can subscribe to calendars with such recurrences, but cannot move them to another calendar.
As a workaround, they both support "every two weeks on Tuesdays", which our Group calendar can also create, but it's not strictly similar and will likely lead to meetings being schedule at wrong dates.

So strictly speaking this isn't a bug in this tool, but I'm leaving the issue open so we can gather ideas on how to improve the situation with clients that don't implement that part of the iCal spec.

**Comment by nigelmegitt** [comment]
The Outlook UI appears to back that up @jean-gui. It allows me to schedule a meeting on any set of days within a week for a weekly recurrence pattern, but only on one specified day for a monthly or yearly pattern, though that monthly day can be "second Tuesday"; the yearly pattern can be "2nd Tuesday every March".

**Comment by nigelmegitt** [comment]
On the "is it a bug" question, it probably makes sense to have a requirement that the calendar files that the tool exports need to work with some set of commonly used major calendar apps, like Outlook, Apple Calendar, Google Calendar etc. which would mean that we need to apply the lowest common denominator constraints to the recurrence patterns that the tool supports, _or_ (perhaps better) provide a way to export recurring events as individual events that can each be imported.

**Comment by vivienlacourba** [comment]
Based on this issue report and seeing what popular calendar apps are doing I suggest that we remove the more advanced possibility to create events that have this kind of recurrence (e.g. "2nd and 4th Tuesdays every month") and limit ourselves to teh simpler version where we can only specify one day e.g. "2nd Tuesdays every month".

@nigelmegitt, @plehegar WDYT?

**Comment by nigelmegitt** [comment]
@vivienlacourba works for me - as per https://github.com/w3c/calendar/issues/25#issuecomment-802676139 otherwise if it's genuinely helpful to have this functionality, allow separate non-recurring meeting invites to be generated from the recurrence pattern and exported as a group.

**Comment by jean-gui** [comment]
@nigelmegitt The problem with sending separate non-recurring notifications is that we would have to potentially send a lot of them every time an important change is made to a recurring event. We could also send a single invite with several non-recurring meetings, but support for that is also extremely variable.

I think the best course of action is to remove the ability for such recurrence patterns, and groups that need it can schedule two recurring meetings instead (for example one every month on the 2nd Monday and one every month on the 4th Monday).

**Comment by plehegar** [comment]
I'm afraid that we won't have a choice here and we will need to have 2 separate event recurrence for this type of cases.

cc @dwsinger

**Comment by jean-gui** [comment]
Done. It's not possible to schedule a monthly meeting two times in a month.
