### ISSUE TITLE
Provide email opt-out

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/calendar#27]
The [announcement of the group calendar tool](https://lists.w3.org/Archives/Member/chairs/2021JanMar/0101.html) says "Group participants and other invited people are notified by email of new meetings and scheduling changes. This can be opted out from your profile [3]". But the link just goes to the "my calendar", which is also available from any other calendar page. There are no links or buttons with text "opt out" or "opt-out" or "email", i.e., if there is a way to opt out as documented, I can't find it in spite of following documentation. A genuine opt-out feature is needed.

**Comment by jean-gui** [comment]
I messed up link numbering in this email as [3] appears before [2] and [1] doesn't appear at all in the text, but [3] does point to https://www.w3.org/users/myprofile/edit, not "my calendar", and contains the field to opt-out. 

Note that emails also contain the link to opt-out ("To stop receiving these emails please update your W3C profile.")

**Comment by michael-n-cooper** [comment]
This is not easy to find, and I shouldn't have to file an issue to get these instructions. In the calendar email, after searching, I find a very small link buried in between two big blocks of content, easy to overlook. Usually unsubscribe features are at the very bottom of an email and use the word "unsubscribe". Also, it would never occur to me to "edit" my profile to opt out of emails, so more breadcrumbs need to be laid. In particular, the "my calendar" should have a clear link.

**Comment by vivienlacourba** [comment]
-1 on using the word "unsubscribe" as it sounds like mailing list or newsletter related.

**Comment by jean-gui** [comment]
@michael-n-cooper I just pushed some changes that should make the option easier to find: there's now a "preferences" link on the "my calendar" page and this link leads to a page dedicated to calendar preferences (with a single option right now, but will likely have more in the future). The link in email notifications will also point to this new page for future notifications.

Regarding the position of the link in the email, it is actually at the very bottom of it. What I believe you see below is your mail client embedding a preview of attached files (the ics invitation here) and I don't think it's possible to do anything about that on our end.

Does that answer your concerns?
