### ISSUE TITLE
Event recurrence is missing in W3C Process CG meetings

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#28]
The W3C Process CG has an usual meeting time of "SECOND and FOURTH WEDNESDAY OF THE MONTH AT 7AM PACIFIC".

I did set it up that way but day recurrence doesn't show up in:
  https://www.w3.org/events/meetings/28d91e83-bc19-408e-816b-32ed7e9bd52e/20210324T070000/edit-future

**Comment by plehegar** [comment]
See also https://github.com/w3c/calendar/issues/25

**Comment by dwsinger** [comment]
nor does anything appear if I ask to edit the meeting?

**Comment by plehegar** [comment]
nothing appears whether you're in edit mode or not, which is a bug.

**Comment by jean-gui** [comment]
You should now be able to edit recurrence patterns when selecting "edit this and future occurrences"
