### ISSUE TITLE
View this event in your browser goes to wrong event

### ISSUE THREAD

**Issue by jnurthen** [w3c/calendar#29]
I have a calendar invite for an event (meeting 25-Mar-21)
https://lists.w3.org/Archives/Public/public-aria/2021Mar/0026.html

The link View this event in your browser goes to the meeting invite from 18-Mar-21

**Comment by jean-gui** [comment]
Thanks @jnurthen, this should be fixed.

**Comment by jnurthen** [comment]
Still broken
