### ISSUE TITLE
View draft events

### ISSUE THREAD

**Issue by chrisn** [w3c/calendar#34]
Is there a link to view a group's draft events? For example, the group calendar page at https://www.w3.org/groups/ig/me/calendar doesn't show draft events that I have created, so I have to bookmark the URL of the draft so that I can return to it.

**Comment by vivienlacourba** [comment]
Hi @chrisn,

You can view drafts events from your "[My calendar / Draft](https://www.w3.org/users/myprofile/calendar/drafts)" page
We are also working on making this info more easily discoverable see proposal I made in another issue https://github.com/w3c/calendar/issues/14#issuecomment-802756837.

Does this answer what you were looking for?

**Comment by chrisn** [comment]
Thank you! I didn't think to check my profile page.

Because I'd created the draft from the group's calendar page, I expected to be able to find the draft in the same place. Is adding a link there possible?

**Comment by jean-gui** [comment]
@chrisn After creating or updating a draft there will now be a message:
![Screenshot_20210401_185918](https://user-images.githubusercontent.com/1479073/113328293-6226a800-931c-11eb-8b25-d8e8db6d8e0c.png)
Do you think that's enough? I'm a bit reluctant to add an additional link on the group calendar page as there are already quite a few of them and I don't think it would be used that often.

**Comment by chrisn** [comment]
This is a useful reminder, thank you! I don't think an additional link is needed, the link in the profile page is enough.
