### ISSUE TITLE
Clearer signaling of joining details

### ISSUE THREAD

**Issue by chrisn** [w3c/calendar#35]
As the meeting organiser, the calendar invite I received has a clear "Joining Instructions" section with the Webex and IRC details I entered. Other recipients don't see this section, and only have the "View this event in your browser" link at the top of the invite. I am concerned that it may not be clear to people that they need to use this link to find the Webex details. Would it be possible to include the "Joining Instructions" section and include the meeting link there - something like "Instructions are restricted to meeting participants, see [link]"?

**Comment by jean-gui** [comment]
Meeting participants should see the joining instructions in the email they receive. Only the mail sent to mailing lists does not contain them (as they are usually public). Did you receive feedback from people telling you the email addressed to them did not contain those instructions?

**Comment by chrisn** [comment]
That makes sense, I was just going by the public mailing list email, so if all member recipients get the joining details directly in the email, this is good.
