### ISSUE TITLE
Join instructions in email

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#36]
https://lists.w3.org/Archives/Public/public-pointer-events/2021JanMar/0116.html

only says
"Instructions are restricted to meeting participants."

and doesn't provide the link provided in the event itself:
 https://lists.w3.org/Archives/Member/member-pointer-events/2019Apr/0000.html

Can we expose the link to the public, or at least provide an option to do so? As a participant, it does make joining the meeting a bit harder compared to
  https://lists.w3.org/Archives/Public/public-pointer-events/2021JanMar/0092.html

**Comment by vivienlacourba** [comment]
Hi @plehegar

The joining link you used in this event should not be a link to your list archive email but it should be a link to directly join the meeting platform (either your webex or zoom link including the meeting password).
This will make it possible for your participants to join in one click.

I will let you correct this link from this page:
  https://www.w3.org/events/meetings/9718517d-0e08-4377-bb7c-07332948233b/20210331T110000/edit-future#joining

Vivien

**Comment by plehegar** [comment]
Thank you Vivien
