### ISSUE TITLE
Include a link back from individual events to the group's calendar

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/calendar#37]
Currently, if you go to view or edit a specific calender item, there is no link back to the owning group's calendar. Adding one would be a useful UI change.

**Comment by jean-gui** [comment]
There are such links on the view page in the participants section (see https://www.w3.org/events/meetings/9806e56e-d780-48bf-b122-7793a9bfe6bc#participants for an example).
I'm not sure how to improve the visibility of those links as there can be multiple groups (an event isn't owned by a group, but a group is a participant of an event).
For the edit form perhaps I could add them somewhere but I fear this might be confusing.

**Comment by vivienlacourba** [comment]
@nigelmegitt see also https://github.com/w3c/calendar/issues/19#issuecomment-800960286

**Comment by nigelmegitt** [comment]
Thanks, I had indeed not noticed that link from the Participants section. I think I'm expecting this to be navigation-like, and therefore at the top.

Since I'm not the only one getting caught out by this, maybe it is worth making a UI change. A couple of proposals to consider:

1. change the link text from "View Calendar" to "View Group Calendar"
2. add a shortcut: button-like labels at the top of the event page, each having the initials of the group participants and a calendar icon, where clicking takes you to that group's calendar.

**Comment by jean-gui** [comment]
I've implemented your first proposal.
For the second, from the screenshot, what do you prefer? Links as badges next to the title and other badges, or after the dates as button?
![Screenshot_20210406_183942](https://user-images.githubusercontent.com/1479073/113747983-3cc4e000-9708-11eb-900c-1e7f87ceba61.png)
I think after the dates is less confusing as people wouldn't necessarily understand they can click on the badges since the "upcoming" and "tentative" ones are not clickable.

**Comment by nigelmegitt** [comment]
My personal preference is for the badges at the top, but either would work well.

**Comment by vivienlacourba** [comment]
cc: @iherman as he had made a similar comment in issue #19.

**Comment by vivienlacourba** [comment]
>  For the second, from the screenshot, what do you prefer? Links as badges next to the title and other badges, or after the dates as button?

Currently our tags are not clickable so it might be confusing to have links here, I woudl therefor suggest we use the option with buttons.

**Comment by jean-gui** [comment]
Following the majority opinion I have added the buttons below the dates.
