### ISSUE TITLE
Show 'Join' link together with 'Joining Instructions' in email

### ISSUE THREAD

**Issue by swickr** [w3c/calendar#38]
When both a Direct Link and Joining Instructions are provided the email that is generated currently shows three separate sections:

> Joining Instructions
> ...
> Participants
> ...
> [Join the meeting]

It is inconvenient that the Joining Instructions and the link to join are separated.

I suggest the 'Join' button be positioned next to the text "Joining Instructions".

**Comment by jean-gui** [comment]
The link (a button in html version) is now located at the top of the joining instructions.
