### ISSUE TITLE
Event Invitation to a Canceled Event

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#41]
This email is a cancellation of a meeting but one has to be careful when reading:
  https://lists.w3.org/Archives/Public/public-w3process/2021Apr/0004.html

I suggest

1. s/Event Invitation/Event Update/ in the email subject
2.  don't include the agenda nor joining instructions

**Comment by jean-gui** [comment]
Fixed. The email now reads "Event canceled".
About your second suggestion, it's also the case on the online view.
