### ISSUE TITLE
Feature request - join meeting link/button location

### ISSUE THREAD

**Issue by scottaohara** [w3c/calendar#42]
hopefully this is a simple request, but could the join meeting control be located at the top of primary content of the calendar page, if not repeat it both at the top and bottom?

on longer meeting / agenda invites, the join meeting can get lost below the fold with all the alternative zoom phone numbers and other provided links

**Comment by vivienlacourba** [comment]
Hi @scottaohara, FYI we had a bit similar request from @swickr in the context of emails and join link/instructions #38.

We are lacking some proper UX work on those pages I hope we can tackle that in a few months once we'll have moved them to the new W3C website design ([WIP project](https://w3c.studio24.net/)).

**Comment by jean-gui** [comment]
@scottaohara I have moved the button to the top of the agenda section. Does that look ok to you?

**Comment by scottaohara** [comment]
yes.  the new positioning is helpful.  thank you
