### ISSUE TITLE
Changes in the WG Calendar now produce duplicate email notifications

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/calendar#45]
It hasn't been the case from the beginning, but starting recently (a few weeks ago) the new Calendar tool sends duplicate email notifications for every eligible entry modification. For example of duplicate email notifications, see [WebFonts WG email list archive](https://lists.w3.org/Archives/Public/public-webfonts-wg/2021Jun/)

**Comment by vivienlacourba** [comment]
Hi @vlevantovsky,

We confirm the issue (that we also noticed for other group calendards) and are looking for what could cause this.

Vivien

**Comment by vlevantovsky** [comment]
The number of duplicate email notifications has increased - I got [three emails addressed to the WG list](https://lists.w3.org/Archives/Public/public-webfonts-wg/2021Jun/) and four emails addressed to me personally after an upcoming event update.

By very strange co-incidence (this is just a hunch) - this is happening after an event was cancelled. The first email cancelled seem to have triggered duplicate notifications, while the most recent increment in duplications is immediately following another cancelled WG call - could this be just a coincidence, or is there a hidden connection? If you look at [the past events in the calendar](https://www.w3.org/groups/wg/webfonts/calendar?past=1&tf=0) - two recent events have been cancelled, one on June 1st, and another one last week, on June 15.

**Comment by jean-gui** [comment]
@vlevantovsky The issue with the cloud has been resolved and I don't think there has been any duplicate emails since. I'm closing the issue but feel free to comment if you notice it happening again.

**Comment by vlevantovsky** [comment]
Thank you @jean-gui @vivienlacourba for resolving this issue. I confirm that the email notifications for our WG call today were sent without any duplication.
