### ISSUE TITLE
Duplicate events in participant's calendar?

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#50]
Rescheduling a calendar event results in duplicated calendar events in the participant's calendar, instead of moving the events. 

via @wareid

@wareid , do you know which client is showing this issue?

**Comment by wareid** [comment]
I've seen it using Outlook for Mac.

**Comment by jean-gui** [comment]
@wareid Do you have an example (name + date + public url of the event) of an event that appears duplicated in your calendar?

I see on https://www.w3.org/groups/wg/epub/calendar that there are duplicates for "Virtual Locators TF". Could this be why you see duplicates in your calendar as well?

It looks like I should delete one of these duplicate series. What do you think?

**Comment by wareid** [comment]
You are welcome to delete all of them, I ended up making new ICS files locally for the group after the duplication fiasco.

**Comment by jean-gui** [comment]
I have left only one series of those events. Do you want me to remove it as well? Are there other events that should be removed?

Also, do you know how you ended up creating all those duplicates? If something's unclear in the UI, we can look into improving it.

**Comment by wareid** [comment]
You can remove the other one, yes. 

If I recall correctly, the duplicates were created when I attempted to cancel the original meeting series and create the new ones instead (we went from a meeting weekly at the same time and day, to same day different alternating times, so I created new occurrences).

**Comment by jean-gui** [comment]
OK, I've removed it. Can I close this ticket or is there anything else requiring some action from me?

**Comment by wareid** [comment]
You can close it!
