### ISSUE TITLE
Meetings can show as being simultaneously Cancelled and In Progress

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/calendar#53]
Just observed this:
![image](https://user-images.githubusercontent.com/4988915/126182042-369318a2-9b2a-433c-9c75-5748c4b9a054.png)

Seems like an impossibility to have a meeting be both cancelled and in progress at the same time!

**Comment by jean-gui** [comment]
Should be an easy fix, I'll work on it very soon.

**Comment by jean-gui** [comment]
OK, I've found the issue. I was looking at a specific event when in fact your screenshot was taken on a list. Fix is deployed.
