### ISSUE TITLE
Indicate who sent the calendar event

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/calendar#55]
During the AC Office hour discussion @TzviyaSiegman noted that when she receives a calendar event she had no idea who invited her.

Currently notification emails sent from the calendar application contain:
> From: W3C Calendar <noreply@w3.org>

Discussing with @plehegar he also thinks that it would be very useful to indicate who triggered an event notification, adding that it should be the person who triggered the notification (which can be different from the personal that initially created the event, e.g. if it was create as a tentative event).

Suggestion based on what Google calendar is doing (and close to what we already do in WBS):
> From: Vivien Lacourba (W3C Calendar) <noreply@w3.org>

**Comment by jean-gui** [comment]
Done. The From: header will now show the name of the person who sent the notification.
