### ISSUE TITLE
Missing time zone in email alternative formats

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#58]
Just received an event confirmation in Thunderbird but the text/plain and the text/html do not say what is the time zone:

--QbysRtnO
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
[...]

 17 August 2021, 12:00 -=
13:00

[...]
--QbysRtnO
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
[...]
&lt;p class=3D"lead" st=
yle=3D"color: #0a0a0a; font-family: Helvetica,Arial,sans-serif; font-weight=
: 400; padding: 0; margin: 0; text-align: left; margin-bottom: 10px; Margin=
-bottom: 10px; font-size: 20px; line-height: 160%;">
                    =
                                            17 August 2021, 12:00
       =
         -13:0&lt;/p>
[...]

Note that the ICS alternative is correct in the email.

![cal-200817](https://user-images.githubusercontent.com/1490400/129776881-e4d3eef5-8668-411a-a60a-85dc12f31b7d.png)

**Comment by jean-gui** [comment]
The timezone should now be displayed.
