### ISSUE TITLE
Remove cancelled meetings from personal icalendar feed

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/calendar#60]
(possibly related to #39)

A confirmed meeting cannot be deleted, only cancelled; but I'm not sure there is any reason for cancelled meetings to still show up in the personal icalendar feed generated for users.

(I understand that `status: cancelled` in `vevent` is useful when sending a cancellation by email for a specific meeting, but I don't think it's useful for the full catalog of events one might synchronize with their calendar app)

**Comment by frivoal** [comment]
Not an expert in calendars, but I suspect that doing what is suggested here would be one way to address #90

**Comment by jean-gui** [comment]
@frivoal This is indeed very much related, let's continue the discussion on #90.

**Comment by dontcallmedom** [comment]
I believe this was done with #90
