### ISSUE TITLE
calendar notices linked in mailing list archive

### ISSUE THREAD

**Issue by brentzundel** [w3c/calendar#63]
This may be a feature rather than a bug, but historically when a message is sent to the entire WG, the message is archived in the WG mailing list.
I don't believe that calendar event update messages, which may be easily sent to an entire WG, are subsequently archived in the same place.

My questions: 
1. is this a feature that could be added, or is it missing deliberately?
2. if it is missing, are such messages archived, if so where?

**Comment by jean-gui** [comment]
Hmm, they should be sent to the WG mailing list, and thus archived by it. Can you give me a link to an event that was not archived?

**Comment by brentzundel** [comment]
I updated [our next event](https://www.w3.org/events/meetings/aef295be-e2eb-41c4-85e0-5a7ca8ef8702/20210908T190000) with an agenda yesterday and selected `Update`, which should have sent an email notification (with subject `Event Updated: VCWG Meeting` to WG members.
I received an email, but the address on the email notification was `brent.zundel@gmail.com` (my W3C member email), not `public-vc-wg@w3.org` (the public WG email).

No email with this subject shows up in [our public archives](https://lists.w3.org/Archives/Public/public-vc-wg/2021Sep/).

I then forwarded the event update notification email to our public mailing list with the new subject `[AGENDA] Verifiable Credentials Working Group (VCWG) Teleconference - 08 Sep 2021` because I wanted it archived so I could link to it.

**Comment by jean-gui** [comment]
Thanks @brentzundel. After investigating, it appears that these emails are stuck in the moderation queue of this list. So the tool did the right thing. I'm now trying to understand why they have to be moderated.

**Comment by brentzundel** [comment]
Thank you for looking into this. If there's anything I might do from my side to help troubleshoot, please let me know.

**Comment by jean-gui** [comment]
OK, if I did everything correctly, those emails shouldn't have to be moderated anymore.
