### ISSUE TITLE
Page that presents a single event lacks affordances to take me back to the group or my calendars

### ISSUE THREAD

**Issue by dwsinger** [w3c/calendar#65]
e.g. I am looking at <https://www.w3.org/events/meetings/28d91e83-bc19-408e-816b-32ed7e9bd52e/20210825T070000> which is a specific instance of a recurring event in a group. I want to look at all the instances, or the group's events, or my events, but there's no 'hierarchy' display or 'up a level' affordance offered

**Comment by vivienlacourba** [comment]
Answered in #75.

Also since the deployment of the new W3C website design the "My calendar" link can be easily found from the "My account" user menu.
