### ISSUE TITLE
subscribe link should contain past events

### ISSUE THREAD

**Issue by dbaron** [w3c/calendar#66]
I went to https://www.w3.org/users/myprofile/calendar , chose the "Export" tab, and used the subscribe link to add the W3C calendar to my calendar.  My W3C calendar currently has 3 past events (one which just ended) and no future events.  However, the link that I got to add to my calendar produces the following ICS file:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.3.5//EN
CALSCALE:GREGORIAN
NAME:My W3C Calendar
X-WR-CALNAME:My W3C Calendar
BEGIN:VTIMEZONE
TZID:UTC
X-MICROSOFT-CDO-TZID:0
BEGIN:STANDARD
DTSTART:20201004T170633
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
TZNAME:UTC
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```

which contains no events.

This means that:
* I can't tell whether the calendar was correctly added in my calendar client
* I have an incorrect view of past events

The link to export should include all events, not just (I presume) future ones.  (I'm presuming that it includes future ones, though I don't actually have any future events, so maybe it's empty for some other reason.)

**Comment by jean-gui** [comment]
ICS files only contain future events indeed. @iherman made a similar comment that he would like to see past events in the ICS as well. Although it may be difficult to show all of them, we could probably at least display events from a few years back.

**Comment by jean-gui** [comment]
Past events are now exported.
