### ISSUE TITLE
Calendar updates not getting sent to mailing list

### ISSUE THREAD

**Issue by jnurthen** [w3c/calendar#70]
I updated agenda and confirmed a meeting today as usual. 
The email came to me with a delay of about 90 mins.

The email was never received on the malling list.

**Comment by jean-gui** [comment]
It looks like these emails are being sent, but then refused by the mailing list server. We are investigating the reason for this.

**Comment by jean-gui** [comment]
We have identified the issue and are working on a fix.

cc @gosko

**Comment by gosko** [comment]
This should now be fixed.
