### ISSUE TITLE
urgent: login broken 

### ISSUE THREAD

**Issue by jnurthen** [w3c/calendar#74]
The login to the calendar isn't working. I log in but the login link still shows at the top right and I cannot edit my calendar entries

**Comment by brentzundel** [comment]
Thanks for opening this. I also am having this issue. Some more details here: https://w3ccommunity.slack.com/archives/C010CACSKAL/p1638369318075000

**Comment by jnurthen** [comment]
Participants are also unable to see meeting joining details due to this

**Comment by jean-gui** [comment]
That seems to be due to an unexpected side-effect of a change we made recently to improve performances. I have reverted that change so the login button should now work properly.

Let me know if you still have issues.
