### ISSUE TITLE
Add a link back to the WG calendar page from the calendar edit page

### ISSUE THREAD

**Issue by r12a** [w3c/calendar#75]
Once you make edits to a calendar event, it's complicated to get back to the event overview page (eg. https://www.w3.org/groups/wg/i18n-core/calendar) because there's no direct link.

Could we add a link?

**Comment by vivienlacourba** [comment]
Hi @r12a, getting back to an old issue which I believe has already been addressed.

An event can be linked to zero, one or multiple groups, so after editing an event you are being redirected to the page that displays the event. If the event is linked to one or more groups you will find next to each group a "`View calendar`" link pointing to their respective calendar.

Example https://www.w3.org/events/meetings/9fe696a0-ddd3-461b-903f-c4494f8a5d3b/

![image](https://github.com/user-attachments/assets/efb89c3d-e8f0-4949-a7e5-7442a9b56b03)

**Comment by vivienlacourba** [comment]
Hi @r12a, getting back to an old issue which I believe has already been addressed.

An event can be linked to zero, one or multiple groups, so after editing an event you are being redirected to the page that displays the event. If the event is linked to one or more groups you will find next to each group a "`View calendar`" link pointing to their respective calendar.

Example https://www.w3.org/events/meetings/9fe696a0-ddd3-461b-903f-c4494f8a5d3b/

![image](https://github.com/user-attachments/assets/efb89c3d-e8f0-4949-a7e5-7442a9b56b03)

**Comment by r12a** [comment]
Thanks @vivienlacourba.   @xfq this is in your ball park now, are you ok with the resolution?

**Comment by xfq** [comment]
Looks good to me. Thank you both!
