### ISSUE TITLE
Add prominent link to minutes from past calendar view

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/calendar#76]
When viewing the past event page of a group (e.g. [for the WebRTC WG](https://www.w3.org/groups/wg/webrtc/calendar?past=1&tf=0), for meetings that have minutes documented, it would be much better if there was a direct link from the list of events to their minutes. Right now, you have to hit "more information", and find a hard-to-spot button at the end of the page to go the minutes.

**Comment by plehegar** [comment]
Bumping this one up.

Without it, some groups are maintaining separate list of minutes:
 https://www.w3.org/Privacy/IG/meetings

**Comment by koalie** [comment]
+1

**Comment by jean-gui** [comment]
Done, see https://www.w3.org/groups/tf/pronunciation-tf/calendar/?past=1&tf=0. How does that look?

**Comment by dontcallmedom** [comment]
much improved, thanks!

**Comment by koalie** [comment]
Excellent! Thank you very much @dontcallmedom and @jean-gui!
@plehegar FYI, I'm going to send a mail to chairs (and other groups in our community) to let them know of this useful enhancement, and remind people to go back to the calendar entry to fill out the "minutes" field.
