### ISSUE TITLE
Joining Instructions: "join the meeting" link has role=button

### ISSUE THREAD

**Issue by pkra** [w3c/calendar#77]
The "join the meeting" link shown after sign-in looks like this `<a href="https://mit.zoom...." class="btn btn-primary" role="button">...</a>`. 

But it's just a link and the role hides that fact (e.g., AT users won't know they can copy a link URL here).

**Comment by jean-gui** [comment]
Fixed, I've removed the role.

**Comment by pkra** [comment]
Thank you @jean-gui -- cc @mcking65 who had brought this on on the ARIA editors call.
