### ISSUE TITLE
add zoom link to personalized export

### ISSUE THREAD

**Issue by pkra** [w3c/calendar#78]
E.g., https://www.w3.org/events/meetings/1f06f919-513f-4341-aa47-2027ee0925c5, after signing in, the "personal" export does not include the zoom link.

**Comment by jean-gui** [comment]
Restricted information should now appear in the export if you are invited to the meeting or have member access. @pkra can you confirm?

**Comment by pkra** [comment]
Thank you @jean-gui looks good to me -- cc @mcking65 who had brought this on on the ARIA editors call.
