### ISSUE TITLE
various issues with the login functionality

### ISSUE THREAD

**Issue by jnurthen** [w3c/calendar#80]
* It is implemented as a link not a button. It looks and performs like a button (I understand it is implemented as a link but it doesn't really perform navigation) so IMO should be a button (note - there will probably be contrary opinions on this)
* The login button / status message is hidden when on viewports less that 992px width. This makes it impossible to tell if you are logged in without expanding the hamburger button. Whether the user is logged in or not is important enough it should not be hidden in any viewport.

**Comment by swickr** [comment]
+1 to displaying the logged-in/not-logged-in state at the top of the window regardless of the window width.  One should not have to open the hamburger menu to be reminded.

**Comment by vivienlacourba** [comment]
This issue was addressed in June 2023 with the launch of the new W3C website design which now shows a clearer logged in state.
