### ISSUE TITLE
Better name for the ICS-exported calendar

### ISSUE THREAD

**Issue by wetneb** [w3c/calendar#86]
Exporting a calendar to ICS should include a name which matches that of the group the calendar corresponds to.

For instance, when importing `https://www.w3.org/groups/cg/reconciliation/calendar/export` in Thunderbird (the calendar for the [Entity Reconciliation Community Group](https://www.w3.org/community/reconciliation/)), the calendar is created in Thunderbird with "export" as a name (probably extracted from the URL). It would be cleaner if it could automatically be named "Entity Reconciliation Community Group" instead.

**Comment by jean-gui** [comment]
The exported file does have a meaningful name:
```
NAME:Entity Reconciliation Community Group Calendar
X-WR-CALNAME:Entity Reconciliation Community Group Calendar
```
Google Calendar seems to honor those properties and names subscribed calendars appropriately, but it looks like Thunderbird doesn't.

I'm closing this issue because unfortunately I don't think there's much we can do to fix this.
