### ISSUE TITLE
ICS export for recurring meetings

### ISSUE THREAD

**Issue by bruce-usab** [w3c/calendar#87]
As a first time user of this service, using `.ics` export from this event:
https://www.w3.org/events/meetings/fdbff191-ae2e-48ee-87d7-37b2b20c653a/20210702T110000

When opened in MS Outlook (Exchange) I ended up with item spanning years rather than reoccurring weekly.

I was not able to figure out how to make the correct, and ended up copy/paste into my own event.  I thought I should report the bug.

**Comment by swickr** [comment]
For the event you identified, the system is reporting what was entered; the meeting is listed as starting in 2021 and ending in 2023:
02 July 2021, 11:00 - 28 April 2023, 12:00

Perhaps the intent was to list this as a recurring daily/weekly/monthly meeting but that's not how it is currently described in the system.  I suggest checking with the chairs of the group for which that meeting was entered.

**Comment by jean-gui** [comment]
Tahnks @swickr, you're right, that meeting has a very long duration, which is likely not intended.
@michael-n-cooper, can you double-check that event and fix it if needed?

**Comment by bruce-usab** [comment]
This meeting should be recurring weekly, Fridays 11:00 U.S. Eastern / Boston.

It might be the case that @alastc has replaced/corrected already.  I reported this bug as it was my understanding that this feature is new.

**Comment by michael-n-cooper** [comment]
@jean-gui I edited the event, it was clearly confusion between duration and repetition, which I see a lot.

**Comment by jean-gui** [comment]
@michael-n-cooper I am working on small improvements to make the distinction between duration and repetition clearer.
