### ISSUE TITLE
governance-tf and bylaws-tf calendars still showing despite being cancelled

### ISSUE THREAD

**Issue by frivoal** [w3c/calendar#90]
Hi,

The governance task force and the bylaws task force have been disbanded, and their future meetings cancelled. However, they still show up in my w3c calendar, and I cannot get rid of them.

If I load up the events in the w3c calendar web-site, they are marked as cancelled (not not deleted), however, that does not appear to propagate to (some?) calendar clients.

Here are screenshots of two clients I've having the same issue in.

Apple calendar:
<img width="536" alt="Screen Shot 2022-11-09 at 8 07 54" src="https://user-images.githubusercontent.com/113268/200696392-e24b1d3a-798a-4762-b010-674341e4a91f.png">

Fastmail calendar:
<img width="540" alt="Screen Shot 2022-11-09 at 8 08 38" src="https://user-images.githubusercontent.com/113268/200696402-0ac1ea15-7300-41b7-84f7-2e629657225c.png">

Since these are events in a shared calendar, I cannot delete them myself, so I cannot help myself.

**Comment by dwsinger** [comment]
similarly, I am subscribed to calendars, and I see GovTF meetings still on the calendar – crossed out, but still taking up visual space

**Comment by frivoal** [comment]
As more and more cancelled meetings pile up in my subscribed calendar, it becomes decreasingly usable.

**Comment by frivoal** [comment]
> So I think we should provide an option per user to choose whether or not to include canceled events in the export. How does that sound?

I'd tick that box if it existed, and I believe it would solve my problem. So yes, assuming that there are also people who would like to keep the box unticked, it sounds like a good idea.

> And in your opinion, should this option also remove them from web views?

Possibly, although I am less sure. Given that the web views do support the cancelled status, that's less critical. And if you're trying to uncancel something, being able to find it is nice. But as now-cancelled-earlier-recurring-meetings pile up, the view gets less and less readable. Anyway, as long as it's an option and you can have it both ways, I suppose that having that choice is a good idea.

**Comment by jean-gui** [comment]
@frivoal @dwsinger Rather than adding an option per user, you can now append `include_canceled=0` to the query string of export URLs to remove canceled events. This new feature is exposed in the export options for all calendars (group and personal) as a checkbox.

This option only works for exports, as it is indeed less important for html views.

Note that I have also edited the bylaws event so that it stops recurring before the first canceled occurrence, as I believe this was the right thing to do.

**Comment by frivoal** [comment]
As far as I can tell, this has solved my problem. Thank you @jean-gui !

I'll report back if I discover anything weird, but so far so good.

**Comment by dwsinger** [comment]
Thanks

that tip could usefully appear in the ‘My W3C’/Calendar page, export tab?

> On Dec 20, 2022, at 02:31, Florian Rivoal ***@***.***> wrote:
> 
> 
> As far as I can tell, this has solved my problem. Thank you @jean-gui !
> I'll report back if I discover anything weird, but so far so good.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

David Singer
Standards Governance, Apple

***@***.***

**Comment by vivienlacourba** [comment]
> Thanks
> 
> that tip could usefully appear in the ‘My W3C’/Calendar page, export tab?

@dwsinger, it does as @jean-gui noted:
> This new feature is exposed in the export options for all calendars (group and personal) as a checkbox.

Screenshot of the "Export" tab in https://www.w3.org/users/myprofile/calendar

![Screenshot 2022-12-20 at 19-23-42 My Calendar](https://user-images.githubusercontent.com/2012282/208739135-0469410b-725d-4dd4-b210-cdc279ed0aa0.png)

**Comment by dwsinger** [comment]
doh, thanks!

> On Dec 20, 2022, at 10:26, Vivien Lacourba ***@***.***> wrote:
> 
> 
> Thanks
> that tip could usefully appear in the ‘My W3C’/Calendar page, export tab?
> @dwsinger, it does as @jean-gui noted:
> This new feature is exposed in the export options for all calendars (group and personal) as a checkbox.
> Screenshot of the "Export" tab in https://www.w3.org/users/myprofile/calendar—
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

David Singer
Standards Governance, Apple

***@***.***
