### ISSUE TITLE
Option to uncancel an event

### ISSUE THREAD

**Issue by egekorkan** [w3c/calendar#92]
Currently, there is no option to uncancel an event in the W3C Calendar. Sometimes, an event is cancelled intentionally but we want to bring it back or sometimes an event, or worse a whole series, is cancelled by mistake and there is no way to revert it.
So it would be nice to add the option to uncancel an event or a series of it. It should be easy to do on the web interface but for outlook invites, it should mean sending a new invitation.

**Comment by csarven** [comment]
To add to this, once a recurring event is cancelled, its repeat until date can no longer be modified - the option disappears.

**Comment by jean-gui** [comment]
It should now be possible to uncancel events.
@csarven AFAICT it is possible to change the recurrence setting of a canceled event, just make sure to edit the series, not a single instance.

**Comment by egekorkan** [comment]
Thanks @jean-gui !
