### ISSUE TITLE
[Performance] "My calendar" page takes much longer to load than the other calendar pages

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/calendar#97]
This is for sure affecting screen reader users, not sure how much this is even noticed without screen readers running.

1. With a screen reader running, get to https://www.w3.org/users/<your_w3c_user_id>/calendar (where you would change <your_w3c_user_id> to your actual id. You can also get to that page from other calendar pages if you follow the link "My calendar".
2. Wait for 10 - 20 seconds  and try to move around through the page using a screen reader command, such as CTRL + Option + right/left arrows if you are using VoiceOver on the Mac, or regular up and down arrow keys if you are using NVDA or JAWS on Windows.

**Expected result**: The page loads and the user is able to use their regular screen reader commands to move around.

**Obtained result**: The browser freezes for a good bit and the user needs to wait significantly longer than 10 - 20 seconds for the page to be usable.

It would be good to have a look at what scripts are running on this page that are not running on the other calendar pages, or at what other things may be different. It affects both JAWS and NVDA with Chrome and Firefox on Windows, as well as VoiceOVer on the mac.

**Comment by vivienlacourba** [comment]
@daniel-montalvo with the move of the calendar application to the new W3C website design does this issue still exist?

**Comment by daniel-montalvo** [comment]
Seems to be much better now with the new redesign.
