### ISSUE TITLE
bogus message when subscribe to an event

### ISSUE THREAD

**Issue by jnurthen** [w3c/calendar#98]
When I subscribe to an event (like the AB-led Member meetings for example) I get the following bogus message
"You haven't sent notifications for this event yet. Edit the event and click on the update button to send them now."

I don't own the event so this seems supurious.

**Comment by vivienlacourba** [comment]
Indeed I'm also seeing that message on https://www.w3.org/events/meetings/ef8e1674-226f-4a8e-8b89-ea98d2b25afb/20230221T090000

**Comment by jean-gui** [comment]
@jnurthen Thanks for reporting this. It should now be fixed.
